# Header
menu:
  Home: /
  Start Here: /start-here
  Subscribe: /subscribe
  Archives: /archives

# Logo Image Source
# logo_src: /images/logo.svg
logo_src: /images/anita-icon.png

# Theme Main Subtitle
subtitle_main: Information Distillery

# # Theme Secondary subtitle
susbtitle_secondary: A blog that does the heavy lifting of research, distilling knowledge down to digestable pieces of information. <br><h3><a href="/start-here">Start Here</a></h3>

# Footer About Section
about_footer: Hi, my name is Anita and I love to learn. This blog is here to capture all the fascinating things I'm learning about. I write code, when I'm not reading, listening to podcasts, climbing or hanging out with people I like.

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:


# Google Analytics Tracking ID
google_analytics: UA-131516982-1

# Social Accounts
twitter_url: https://twitter.com/Neats29
instagram_url: https://www.instagram.com/Neats29
github_url: https://github.com/Neats29
email_url: mailto:baadge29@gmail.com

# stops markdown from adding <br> tags when adding html in markdown
marked:
  gfm: true
  breaks: false
